# Generated by Django 5.1.3 on 2024-11-26 13:34

import utils.model_valitators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicons/%Y/%m/', validators=[utils.model_valitators.validate_png]),
        ),
    ]
